# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'GitHubSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppNotUsingStoryboard
  # UI
  pod 'PKHUD', '~> 5.0'
  pod 'FontAwesome.swift'
  
  # Utility
  pod 'R.swift'
  pod 'LicensePlist'

  target 'GitHubSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubSearchUITests' do
    # Pods for testing
  end

end
